---
locale: fr
ui-strings: null
header:
  title: Questionnaire OSPO
  logo: ""
  color: is-primary
  subtitle: A subtitle here, possibly with _markdown_ formatting.
footer:
  text: Some text here, possibly with **markdown** formatting.
  contact: ""
mail-to: null
display-help: true
display-summary: true
display-score: true
display-score-details: true
display-score-top-result: true
conditional-navigation: false
display-unconditionnally: ""
score-variables:
  score-1:
    display: Score for 1
    value: 0
    as-top-result-display: 1 wins :)
  score-2:
    display: Score for 2
    value: 0
    max: 10
    as-top-result-display: 2 wins :(
conditional-score-outputs:
  cas-1:
    notification: is-success
    priority: 1
    message: "1 wins! :)  Here is the score 1: %score-1"
    condition-1:
      score-1: 1
  cas-2:
    notification: is-danger
    message: "2 wins! :(  Here is the score 2: %score-2"
    condition-1:
      score-2: 9
tree:
  - node: "0"
    text: Paré à commencer ?
    home-page: true
    force-help: true
    no-summary: true
    help: Some introductory text here.
    choices:
      - answer: Oui !
        goto: "1"
        color: is-info
  - node: "1"
    progress: "[1 3]"
    text: Y a-t-il une personne ou une équipe dédiée au logiciel libre/ à l'open
      source ?
    help: Some **help text** here for the first question.  Markdown formatting
      accepted.
    start-page: true
    choices:
      - answer: "1"
        summary: Vous êtes la seule personne dédiée au logiciel libre/ à l'open source.
        explain: Some explanation here.
        score:
          score-1:
            value: 1
        goto: "2"
        color: is-info
      - answer: 2 à 4
        summary: Votre équipe contient 2 à 4 personnes dédiées au logiciel libre/ à
          l'open source
        color: is-warning
        goto: "2"
      - answer: plus de 4
        summary: Votre équipe contient plus de 4 personnes dédiées au logiciel libre/ à
          l'open source
        color: is-warning
        goto: "2"
  - node: "2"
    progress: "[2 3]"
    text: Cette équipe est-elle pluridisciplinaire ?
    help: C'est-à-dire avec un traitement des questions légales, techniques, de
      gouvernance et de communauté
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe est pluridisciplinaire
        score:
          score-2:
            value: 10
        goto: "3"
      - answer: En partie/en cours
        summary: Votre équipe est presque pluridisciplinaire
        score:
          score-2:
            value: 10
        goto: "3"
        color: is-info
      - answer: No
        summary: Votre équipe n'est pas pluridisciplinaire.
        color: is-warning
        goto: end
  - node: "3"
    progress: "[3 3]"
    text: L'équipe déploie-t-elle une stratégie open source ?
    help: Some help text here for the second question.
    choices:
      - answer: Oui
        summary: Votre équipe déploie une stratégie open source
        goto: "4"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe est en train de déploiyer une stratégie open source
        goto: "4"
        color: is-info
      - answer: Non
        summary: Votre équipe n'a pas de stratégie open source.
        color: is-warning
        goto: end
  - node: "4"
    progress: "[4 3]"
    text: "Cette stratégie s'intéresse-t-elle à :"
    help: Some help text here for the second question.
    choices:
      - answer: Oui
        summary: Votre équipe déploie une stratégie open source
        goto: "4"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe est en train de déploiyer une stratégie open source
        goto: "4"
        color: is-info
      - answer: Non
        summary: Votre équipe n'a pas de stratégie open source.
        color: is-warning
        goto: end
  - node: "5"
    progress: "[5 3]"
    text: L'équipe dispose-t-elle d'un portail de présentation (site web) ?
    help: Some help text here for the second question.
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe dispose d'un portail de présentation.
        goto: "6"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe est en train de s'équiper d'un portail de présentation.
        goto: "6"
        color: is-info
      - answer: Non
        summary: Votre équipe n'a pas de portail de présentation.
        color: is-warning
        goto: end
  - node: "6"
    progress: "[6 3]"
    text: L'équipe dispose-t-elle d'un catalogue de recommandation de logiciels
      libres ?
    help: Some help text here for the second question.
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe dispose d'un catalogue de recommandation de logiciels
          libres.
        goto: "7"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe est en train de s'équiper d'un catalogue de recommandation
          de logiciels libres.
        goto: "7"
        color: is-info
      - answer: Non
        summary: Votre équipe n'a pas de catalogue de recommandation de logiciels
          libres.
        color: is-warning
        goto: end
  - node: "7"
    progress: "[7 3]"
    text: L'équipe dispose-t-elle d'une liste de dépôts publiés ?
    help: Par exemple le SILL pour la mission logiciels libres de la DINUM
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe dispose d'une liste de dépôts publiés.
        goto: "8"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe est en train de créer une liste de dépôts publiés.
        goto: "8"
        color: is-info
      - answer: Non
        summary: Votre équipe n'a pas de liste de dépôts publiés.
        color: is-warning
        goto: end
  - node: "8"
    progress: "[8 3]"
    text: L'équipe dispose-t-elle d'une liste des licences utilisables ?
    help: ""
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe dispose d'une liste des licences utilisables.
        goto: "9"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe est en train de créer une liste des licences utilisables.
        goto: "9"
        color: is-info
      - answer: Non
        summary: Votre équipe n'a pas de liste des licences utilisables.
        color: is-warning
        goto: end
  - node: "9"
    progress: "[9 3]"
    text: L'équipe dispose-t-elle de manière générale d'une documentation ?
    help: ""
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe dispose de manière générale d'une documentation.
        goto: "10"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe dispose en partie d'une documentation.
        goto: "10"
        color: is-info
      - answer: Non
        summary: Votre équipe n'a pas de documentation.
        color: is-warning
        goto: end
  - node: "10"
    progress: "[10 3]"
    text: L'équipe est-elle parvenue à mettre en lien et à créer du lien avec les
      membres de son organisation ?
    help: ""
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe est parvenue à mettre en lien et à créer du lien avec les
          membres de son organisation.
        goto: "11"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe est en train de mettre en lien et de créer du lien avec
          les membres de son organisation.
        goto: "11"
        color: is-info
      - answer: Non
        summary: Votre équipe ne met pas en lien et n'a pas de lien avec les membres de
          son organisation.
        color: is-warning
        goto: end
  - node: "11"
    progress: "[11 3]"
    text: L'équipe fait-elle la promotion du logiciel libre ?
    help: Elle explique son intérêt, ses avantages, et indique les bonnes pratiques
      à adopter.
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe fait la promotion du logiciel libre.
        goto: "12"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe commence à faire la promotion du logiciel libre.
        goto: "12"
        color: is-info
      - answer: Non
        summary: Votre équipe ne fait pas la promotion du logiciel libre.
        color: is-warning
        goto: end
  - node: "12"
    progress: "[12 3]"
    text: L'équipe fait-elle la promotion du logiciel libre de manière globale, en
      dehors de son organisation ?
    help: ""
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe fait la promotion du logiciel libre en dehors de son
          organisation.
        goto: "13"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe commence à faire la promotion du logiciel libre en dehors
          de son organisation.
        goto: "13"
        color: is-info
      - answer: Non
        summary: Votre équipe ne fait pas la promotion du logiciel libre en dehors de
          son organisation.
        color: is-warning
        goto: end
  - node: "13"
    progress: "[13 3]"
    text: L'équipe incite-t-elle ses membres à contribuer à des projets open source
      en dehors de ses propres produits logiciels ?
    help: ""
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe incite ses membres à contribuer à des projets open source
          en dehors de ses propres produits logiciels.
        goto: "14"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe commence à inciter ses membres à contribuer à des projets
          open source en dehors de ses propres produits logiciels.
        goto: "14"
        color: is-info
      - answer: Non
        summary: Votre équipe n'incite pas ses membres à contribuer à des projets open
          source en dehors de ses propres produits logiciels.
        color: is-warning
        goto: end
  - node: "14"
    progress: "[14 3]"
    text: L'équipe incite-t-elle ses membres à contribuer à des projets open source
      en dehors de ses propres produits logiciels ?
    help: ""
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe incite ses membres à contribuer à des projets open source
          en dehors de ses propres produits logiciels.
        goto: "15"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe commence à inciter ses membres à contribuer à des projets
          open source en dehors de ses propres produits logiciels.
        goto: "15"
        color: is-info
      - answer: Non
        summary: Votre équipe n'incite pas ses membres à contribuer à des projets open
          source en dehors de ses propres produits logiciels.
        color: is-warning
        goto: end
  - node: "15"
    progress: "[15 3]"
    text: L'équipe est-elle en lien avec d'autres membres d'associations,
      d'entreprises, de la communauté du libre ?
    help: ""
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe est en lien avec d'autres membres d'associations,
          d'entreprises, de la communauté du libre.
        goto: "16"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe commence à être en lien avec d'autres membres
          d'associations, d'entreprises, de la communauté du libre.
        goto: "16"
        color: is-info
      - answer: Non
        summary: Votre équipe n'est pas en lien avec d'autres membres d'associations,
          d'entreprises, de la communauté du libre.
        color: is-warning
        goto: end
  - node: "16"
    progress: "[16 16]"
    text: L'équipe collabore-t-elle avec ces membres ?
    help: ""
    choices:
      - answer: Oui tout à fait
        summary: Votre équipe collabore avec d'autres membres d'associations,
          d'entreprises, de la communauté du libre.
        goto: "16"
        color: is-info
      - answer: En partie/en cours
        summary: Votre équipe commence à collaborer avec d'autres membres
          d'associations, d'entreprises, de la communauté du libre.
        goto: "16"
        color: is-info
      - answer: Non
        summary: Votre équipe ne collabore pas avec d'autres membres d'associations,
          d'entreprises, de la communauté du libre.
        color: is-warning
        goto: end
  - node: end
    text: This is the end.
    done: true
