---
locale: fr
ui-strings: null
header:
  title: Questionnaire OSPO
  logo: ""
  color: is-primary
  subtitle: Voici un questionnaire sur votre OSPO, vous permettant de connaître votre degré d'ospoïsation !
footer:
  text: Mission logiciels libres de la DINUM - [code.gouv.fr](https://code.gouv.fr)
  contact: ""

mail-to: null
display-help: true
display-summary: true
display-score: true
display-score-details: true
display-score-top-result: true
conditional-navigation: false
display-unconditionnally: ""

score-variables:
  score-1:
    display: Votre score OSPO
    value: 0

conditional-score-outputs:
  cas-1:
    notification: is-success
    priority: 1
    message: "Top OSPO! (%score-1)"
    condition-1:
      score-1: 10
  cas-2:
    notification: is-danger
    message: "OSPO à créer... (%score-1)"
    condition-1:
      score-1: 0

tree:
  - node: "0"
    text: Paré à commencer ?
    home-page: true
    force-help: true
    no-summary: true
    help: Vous vous apprétez à répondre à un questionnaire de 18 questions. Cela ne vous prendra que 5 petites minutes.
    choices:
      - answer: Oui !
        goto: "1"
        color: is-info
  - node: "1"
    progress: "[1 18]"
    text: Y a-t-il une personne ou une équipe dédiée au logiciel libre / à l'open
      source au sein de votre organisation ?
    help: "Dans l'idéal, il s'agit d'une équipe avec des équivalent temps plein, mais il faut bien commencer quelque part !"
    start-page: true
    choices:
      - answer: plus de 4
        summary: Votre équipe contient plus de 4 personnes dédiées au logiciel libre / à
          l'open source.
        color: is-success
        goto: "2"
        score:
          score-1:
            value: 3
      - answer: 2 à 4
        summary: Votre équipe contient 2 à 4 personnes dédiées au logiciel libre / à l'open source
        color: is-primary.
        goto: "2"
        score:
          score-1:
            value: 2
      - answer: "1"
        summary: Vous êtes la seule personne dédiée au logiciel libre / à l'open source. 
        score:
          score-1:
            value: 1
        goto: "2"
        color: is-info
      - answer: "0"
        summary: Vous n'avez pas encore de personne dédiée au logiciel libre dans votre structure.
        goto: "2"
        color: is-warning
  - node: "2"
    progress: "[2 18]"
    text: Cette équipe est-elle pluridisciplinaire ?
    help: C'est-à-dire avec un traitement des questions légales, techniques, de gouvernance et de communauté
    choices:
      - answer: Oui
        summary: Votre équipe est pluridisciplinaire.
        color : is-success
        score:
          score-1:
            value: 2
        goto: "3"
      - answer: En cours
        summary: Votre équipe est presque pluridisciplinaire.
        score:
          score-1:
            value: 1
        goto: "3"
        color: is-info
      - answer: Non
        summary: Votre équipe n'est pas pluridisciplinaire.
        color: is-warning
        goto: "3"
  - node: "3"
    progress: "[3 18]"
    text: "L'équipe déploie-t-elle une stratégie open source ?"
    help: "Il s'agit de décrire clairement la stratégie open source de l'organisation, autrement dit en quoi elle consiste, dans quel but elle est mise en place et comment est-elle mise en oeuvre. Par exemple pour l'OSPO de la DINUM, sa stratégie se résume ainsi : [utiliser, publier, attirer](https://code.gouv.fr/fr/)." 
    choices:
      - answer: Oui
        summary: Votre équipe déploie une stratégie open source.
        goto: "4"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe est en train de déploiyer une stratégie open source.
        goto: "4"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe n'a pas de stratégie open source.
        color: is-warning
        goto: end
  - node: "4"
    progress: "[4 18]"
    text: "Cette stratégie s'intéresse-t-elle : à l’utilisation de l’open source, du logiciel libre et au développement de logiciels ?"
    help: 
    choices:
      - answer: Oui
        summary: Votre équipe déploie une stratégie open source.
        goto: "5"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe est en train de déploiyer une stratégie open source.
        goto: "5"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe n'a pas de stratégie open source.
        color: is-warning
        goto: "5"
  - node: "5"
    progress: "[5 18]"
    text: "Cette stratégie s'intéresse-t-elle : au fait d’attirer des compétences métiers ?"
    help: 
    choices:
      - answer: Oui
        summary: Votre équipe s'intéresse au fait d'attirer des compétences métiers.
        goto: "6"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe commence à s'intéresser au fait d'attirer des compétences métiers. 
        goto: "6"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe ne se préoccupe pas d'attirer des compétences métiers.
        color: is-warning
        goto: "6"
  - node: "6"
    progress: "[6 18]"
    text: "Cette stratégie s'intéresse-t-elle : aux moyens permettant la mise en oeuvre de la stratégie (moyens juridiques, financiers et humains) ?"
    help: 
    choices:
      - answer: Oui
        summary: Votre équipe s'intéresse aux moyens permettant la mise en oeuvre de la stratégie.
        goto: "7"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe commence à s'intéresser aux moyens permettant la mise en oeuvre de la stratégie. 
        goto: "7"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe ne se préoccupe pas des moyens permettant la mise en oeuvre de la stratégie.
        color: is-warning
        goto: "7"
  - node: "7"
    progress: "[7 18]"
    text: L'équipe dispose-t-elle d'un portail de présentation (site web) ?
    help: 
    choices:
      - answer: Oui
        summary: Votre équipe dispose d'un portail de présentation.
        goto: "8"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe est en train de s'équiper d'un portail de présentation.
        goto: "8"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe n'a pas de portail de présentation.
        color: is-warning
        goto: "8"
  - node: "8"
    progress: "[8 18]"
    text: L'équipe dispose-t-elle d'un catalogue de recommandation de logiciels
      libres ?
    help: On peut prendre exemple sur le [Socle interministériel des logiciels libres (SILL)](https://sill.code.gouv.fr/).
    choices:
      - answer: Oui 
        summary: Votre équipe dispose d'un catalogue de recommandation de logiciels
          libres.
        goto: "9"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe est en train de s'équiper d'un catalogue de recommandation
          de logiciels libres.
        goto: "9"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe n'a pas de catalogue de recommandation de logiciels
          libres.
        color: is-warning
        goto: "9"
  - node: "9"
    progress: "[9 18]"
    text: L'équipe dispose-t-elle d'une liste de dépôts publiés ?
    help: Par exemple [CodeGouv](https://code.gouv.fr/public/#/repos).
    choices:
      - answer: Oui
        summary: Votre équipe dispose d'une liste de dépôts publiés.
        goto: "10"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe est en train de créer une liste de dépôts publiés.
        goto: "10"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe n'a pas de liste de dépôts publiés.
        color: is-warning
        goto: "10"
  - node: "10"
    progress: "[10 18]"
    text: L'équipe dispose-t-elle d'une liste des licences utilisables ?
    help: Voir la documentation mise à disposition sur le site de la [Mission logiciels libres](https://www.data.gouv.fr/fr/pages/legal/licences/).
    choices:
      - answer: Oui
        summary: Votre équipe dispose d'une liste des licences utilisables.
        goto: "11"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe est en train de créer une liste des licences utilisables.
        goto: "11"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe n'a pas de liste des licences utilisables.
        color: is-warning
        goto: "11"
  - node: "11"
    progress: "[11 18]"
    text: L'équipe dispose-t-elle de manière générale d'une documentation ?
    help: Voir la [documentation](https://code.gouv.fr/fr/doc/) sur CodeGouv. 
    choices:
      - answer: Oui 
        summary: Votre équipe dispose de manière générale d'une documentation.
        goto: "12"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe dispose en partie d'une documentation.
        goto: "12"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe n'a pas de documentation.
        color: is-warning
        goto: "12"
  - node: "12"
    progress: "[12 18]"
    text: L'équipe est-elle parvenue à mettre en lien et à créer du lien avec les
      membres de son organisation ?
    help: La Mission logiciels libres est parvenue à rassembler une communauté d'agents publics appelée [BlueHats](https://code.gouv.fr/fr/bluehats/).
    choices:
      - answer: Oui 
        summary: Votre équipe est parvenue à mettre en lien et à créer du lien avec les
          membres de son organisation.
        goto: "13"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe est en train de mettre en lien et de créer du lien avec
          les membres de son organisation.
        goto: "13"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe ne met pas en lien et n'a pas de lien avec les membres de
          son organisation.
        color: is-warning
        goto: "13"
  - node: "13"
    progress: "[13 18]"
    text: L'équipe fait-elle la promotion du logiciel libre ?
    help: Elle explique son intérêt, ses avantages, et indique les bonnes pratiques
      à adopter.
    choices:
      - answer: Oui 
        summary: Votre équipe fait la promotion du logiciel libre.
        goto: "14"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe commence à faire la promotion du logiciel libre.
        goto: "14"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe ne fait pas la promotion du logiciel libre.
        color: is-warning
        goto: "14"
  - node: "14"
    progress: "[14 18]"
    text: L'équipe fait-elle la promotion du logiciel libre de manière globale, en
      dehors de son organisation ?
    help: ""
    choices:
      - answer: Oui 
        summary: Votre équipe fait la promotion du logiciel libre en dehors de son
          organisation.
        goto: "15"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe commence à faire la promotion du logiciel libre en dehors
          de son organisation.
        goto: "15"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe ne fait pas la promotion du logiciel libre en dehors de
          son organisation.
        color: is-warning
        goto: "15"
  - node: "15"
    progress: "[15 18]"
    text: L'équipe incite-t-elle ses membres à contribuer à des projets open source
      en dehors de ses propres produits logiciels ?
    help: ""
    choices:
      - answer: Oui
        summary: Votre équipe incite ses membres à contribuer à des projets open source
          en dehors de ses propres produits logiciels.
        goto: "16"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe commence à inciter ses membres à contribuer à des projets
          open source en dehors de ses propres produits logiciels.
        goto: "16"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe n'incite pas ses membres à contribuer à des projets open
          source en dehors de ses propres produits logiciels.
        color: is-warning
        goto: "16"
  - node: "16"
    progress: "[16 18]"
    text: L'équipe incite-t-elle ses membres à contribuer à des projets open source
      en dehors de ses propres produits logiciels ?
    help: ""
    choices:
      - answer: Oui
        summary: Votre équipe incite ses membres à contribuer à des projets open source
          en dehors de ses propres produits logiciels.
        goto: "17"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe commence à inciter ses membres à contribuer à des projets
          open source en dehors de ses propres produits logiciels.
        goto: "17"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe n'incite pas ses membres à contribuer à des projets open
          source en dehors de ses propres produits logiciels.
        color: is-warning
        goto: "17"
  - node: "17"
    progress: "[17 18]"
    text: L'équipe est-elle en lien avec d'autres membres d'associations,
      d'entreprises, de la communauté du libre ?
    help: ""
    choices:
      - answer: Oui 
        summary: Votre équipe est en lien avec d'autres membres d'associations,
          d'entreprises, de la communauté du libre.
        goto: "18"
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe commence à être en lien avec d'autres membres
          d'associations, d'entreprises, de la communauté du libre.
        goto: "18"
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe n'est pas en lien avec d'autres membres d'associations,
          d'entreprises, de la communauté du libre.
        color: is-warning
        goto: "18"
  - node: "18"
    progress: "[18 18]"
    text: L'équipe collabore-t-elle avec ces membres ?
    help: ""
    choices:
      - answer: Oui 
        summary: Votre équipe collabore avec d'autres membres d'associations,
          d'entreprises, de la communauté du libre.
        goto: end
        color: is-success
        score:
          score-1:
            value: 2
      - answer: En cours
        summary: Votre équipe commence à collaborer avec d'autres membres
          d'associations, d'entreprises, de la communauté du libre.
        goto: end
        color: is-info
        score:
          score-1:
            value: 1
      - answer: Non
        summary: Votre équipe ne collabore pas avec d'autres membres d'associations,
          d'entreprises, de la communauté du libre.
        color: is-warning
        goto: end
  - node: end
    text: Vous avez fini le questionnaire. Voyons voir ce que ça donne.
    done: true
